# Generated by Django 4.2.19 on 2025-02-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
    ]
